version: 1 # NOTE: this is rails-specific and doesn't have any setup stencils and helm releases, you'll need to use the general one or add the setup yourself.
steps:
  - name: setup
    command: bash -c 'cx snapshots render --stack "${application.display_name}" --snapshot ${snapshot.uuid} --formation ${formation.uuid} --filter "setup" | kubectl apply -f - '
    preflights:
      - command: "cx version"
        message: "It looks like you don't have cx installed! This page can help you install it https://help.cloud66.com/skycap/quickstarts/using-cloud66-toolbelt.html"
      - command: "kubectl version"
        message: "It looks like you don't have kubectl installed! This page can help you install it https://kubernetes.io/docs/tasks/tools/install-kubectl/"
${repeat_inline("_helm_upgrade@ruby-rails.yml", 2, fetch(concat("$.stack.helm.releases[?(@.formation.name==",formation.name,")]")))}
  - name: ruby-rails-db-migrate-cleanup
    command: bash -c 'kubectl delete -n ${formation.name} job ruby-rails-db-migration | true'
    depends_on: ["setup"]
  - name: ruby-rails-db-migrate
    depends_on: ["ruby-rails-db-migrate-cleanup"]
    command: bash -c 'cx snapshots render --stack "${application.display_name}" --snapshot ${snapshot.uuid} --formation ${formation.uuid} --filter "migration" | kubectl apply -f -'
    timeout: 3600s
    probe:
      command: bash -c 'kubectl wait -n ${formation.name} --for=condition=complete --timeout=1800s job ruby-rails-db-migration'
  - name: ruby-rails-deploy
    depends_on: ["ruby-rails-db-migrate"]
    command: bash -c 'cx snapshots render --stack "${application.display_name}" --snapshot ${snapshot.uuid} --formation ${formation.uuid} | kubectl apply -f -'
