# this is a Stencil for Kubernetes deployments
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: ${formation}
  name: ${concat(service, "-deploy")}
  annotations:
    cloud66.com/formation-uuid: ${formation["uuid"]}
    cloud66.com/stencil-uuid: ${stencil["uuid"]}
    cloud66.com/snapshot-uid: ${snapshot["uid"]}
    cloud66.com/snapshot-gitref: ${snapshot["gitref"]}
    cloud66.com/service-name: ${service}
spec:
  selector:
    matchLabels:
      app: ${stackname}
      tier: ${service}
  template:
    metadata:
      labels: # be careful changing labels. It can break your deployment
        app: ${stackname}
        tier: ${service}
    spec:
      containers:
        - name: ${service}
          image: ${concat(repo, "/", image(repo, "name"), ":", image(repo, "tag"))}
          ports: # Comment out this (and the line below) if don't need to expose any ports for this pod
            - containerPort: ${require("INTERNAL_PORT")}
          command: ["bundle", "exec", "rails", "server"]
          args: ["-e", "$(RAILS_ENV)", "-b", "0.0.0.0"]
          env:
            - name: RAILS_ENV
              value: ${env("RAILS_ENV")}
            - name: SECRET_KEY_BASE
              value: ${env("SECRET_KEY_BASE")}
            ${if(configstore("mysql.present", application["configstore_namespace"], "false")=="true",inline("_mysql@cloud66.yml", 12),"")}
            ${if(configstore("redis.present", application["configstore_namespace"], "false")=="true",inline("_redis@cloud66.yml", 12),"")}
            ${if(configstore("postgresql.present", application["configstore_namespace"], "false")=="true",inline("_postgresql@cloud66.yml", 12),"")}
            ${if(configstore("mongodb.present", application["configstore_namespace"], "false")=="true",inline("_mongodb@cloud66.yml", 12),"")}
      imagePullSecrets:
      - name: cloud66-registry-pull-secret
