# this is a Stencil for Kubernetes deployments
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: ${formation}
  name: ${concat(service, "-dep")}
  annotations:
    cloud66.com/formation-uuid: ${formation["uuid"]}
    cloud66.com/stencil-uuid: ${stencil["uuid"]}
    cloud66.com/snapshot-uid: ${snapshot["uid"]}
    cloud66.com/snapshot-gitref: ${snapshot["gitref"]}
    cloud66.com/service-name: ${service}
spec:
  template:
    metadata:
      labels: # be careful changing labels. It can break your deployment
        app: ${stackname}
        tier: ${service}
    spec:
      containers:
        - name: ${service}
          image: ${concat(repo, "/", image(repo, "name"), ":", image(repo, "tag"))}
          ports: # Comment out this (and the line below) if don't need to expose any ports for this pod
            - containerPort: ${require("INTERNAL_PORT")}
          command: ["bundle", "exec", "rails", "server"]
          args: ["-e", "$(RAILS_ENV)", "-b", "0.0.0.0"]
          env:
            - name: "RAILS_ENV"
              valueFrom:
                secretKeyRef:
                  name: ${concat(formation, "-environment-variables")}
                  key: "RAILS_ENV"
            - name: "SECRET_KEY_BASE"
              valueFrom:
                secretKeyRef:
                  name: ${concat(formation, "-environment-variables")}
                  key: "SECRET_KEY_BASE"
            ${if(configstore("mysql.present")=="true",inline("_mysql.yml", 12))}
            ${if(configstore("redis.present")=="true",inline("_redis.yml", 12))}
            ${if(configstore("mongodb.present")=="true",inline("_mongodb.yml", 12))}
            ${if(configstore("postgresql.present")=="true",inline("_postgresql.yml", 12))}
      imagePullSecrets:
      - name: cloud66-registry-pull-secret
