#!remove-empty
# this is a Stencil for Kubernetes deployments
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: ${formation.name}
  name: ${concat(service.name, "-deploy")}
  annotations:
    cloud66.com/service-name: ${service.name}
spec:
  selector:
    matchLabels:
      app: ${application.name}
      tier: ${service.name}
  template:
    metadata:
      labels: # be careful changing labels. It can break your deployment
        app: ${application.name}
        tier: ${service.name}
    spec:
      containers:
        - name: ${service.name}
          image: ${concat(repo, "/", image(repo, "name"), ":", image(repo, "tag"))}
          ports: # Comment out this (and the line below) if don't need to expose any ports for this pod
            - containerPort: ${service.port.container}
          command: ["bundle", "exec", "rails", "server"]
          args: ["-e", "$(RAILS_ENV)", "-b", "0.0.0.0"]
          env:
            - name: RAILS_ENV
              value: ${env("RAILS_ENV")}
            - name: SECRET_KEY_BASE
              value: ${env("SECRET_KEY_BASE")}
            ${if(configstore("mysql.present", application.configstore_namespace, "false")=="true",inline("_mysql@cloud66.yml", 12),"")}
            ${if(configstore("redis.present", application.configstore_namespace, "false")=="true",inline("_redis@cloud66.yml", 12),"")}
            ${if(configstore("postgresql.present", application.configstore_namespace, "false")=="true",inline("_postgresql@cloud66.yml", 12),"")}
            ${if(configstore("mongodb.present", application.configstore_namespace, "false")=="true",inline("_mongodb@cloud66.yml", 12),"")}
      imagePullSecrets:
      - name: cloud66-registry-pull-secret
