apiVersion: batch/v1
kind: Job
metadata:
  name: ${concat(service, "-mig")}
  namespace: ${formation}
  annotations:
    cloud66.com/formation-uuid: ${formation["uuid"]}
    cloud66.com/stencil-uuid: ${stencil["uuid"]}
    cloud66.com/snapshot-uid: ${snapshot["uid"]}
    cloud66.com/snapshot-gitref: ${snapshot["gitref"]}
    cloud66.com/service-name: ${service}
spec:
  template:
    metadata:
      labels: # be careful changing labels. It can break your deployment
        app: ${stackname}
        tier: ${service}
    spec:
      containers:
        - name: ${concat(service, "-mig")}
          image: ${concat(repo, "/", image(repo, "name"), ":", image(repo, "tag"))}
          command: ["bundle", "exec", "rails", "db:migrate"]
      restartPolicy: Never
  backoffLimit: 0