apiVersion: batch/v1
kind: Job
metadata:
  name: ruby-rails-db-migration
  namespace: ${formation.name}
  annotations:
    cloud66.com/service-name: ${service.name}
spec:
  template:
    metadata:
      labels: # be careful changing labels. It can break your deployment
        app: ${application.name}
        tier: ${service.name}
    spec:
      containers:
        - name: ruby-rails-db-migration
          image: ${concat(repo, "/", image(repo, "name"), ":", image(repo, "tag"))}
          command: ["bundle", "exec", "rake", "db:migrate"]
          env:
            - name: RAILS_ENV
              value: ${env("RAILS_ENV")}
            - name: SECRET_KEY_BASE
              value: ${env("SECRET_KEY_BASE")}
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
            ${inline_matching("_(.*?)_credentials@cloud66", 12)}
      restartPolicy: Never
      imagePullSecrets:
        - name: cloud66-registry-pull-secret
  backoffLimit: 0
